// const list_eng = [
//   //HACK B
//   // unit 1
//   ["usual", "thông thường"],
//   ["dust", "quét bụi"],
//   ["weekday", "ngày trong tuần"],
//   ["pull", "kéo"],
//   ["fold", "gấp (quần áo)"],
//   ["reach", "với tới"],
//   ["iron", "là, ủi"],
// ]

const list_eng = [
  //HACK B
  // unit 1
  ["usual", "thông thường"],
  ["dust", "quét bụi"],
  ["weekday", "ngày trong tuần"],
  ["pull", "kéo"],
  ["fold", "gấp (quần áo)"],
  ["reach", "với tới"],
  ["iron", "là, ủi"],
  ["upstairs", "tầng trên"],
  ["sweep", "quét"],
  ["elevator", "thang máy"],
  ["turn on", "bật lên"],
  ["receipt", "hóa đơn"],
  ["count", "đếm"],
  ["press", "nhấn"],
  ["hang", "treo, phơi"],
  ["shut", "đóng"],
  ["laundry", "quần áo cần giặt"],
  ["refill", "làm đầy lại"],
  ["put on", "mặc vào"],
  ["role", "vai trò"],
  ["tend", "có xu hướng, thường"],
  ["shower", "việc tắm rửa"],
  ["arrive", "tới nơi"],
  ["typical", "điển hình"],
  ["get up", "thức dậy"],
  ["flow", "chảy, luồng"],
  ["noon", "buổi trưa"],
  ["routine", "nếp sinh hoạt"],
  ["shit", "ca làm"],
  ["come back", "quay lại"],
  // Unit 2
  ["bother", "làm phiền"],
  ["sit around", "ngồi không"],
  ["sun set", "hoàng hôn"],
  ["garbage", "rác"],
  ["midnight", "nửa đêm"],
  ["tough", "khó khăn"],
  ["sleepy", "buồn ngủ"],
  ["slightly", "hơi hơi"],
  ["awake", "tỉnh, tỉnh táo"],
  ["slip", "trượt chân"],
  ["alone", "một mình"],
  ["push", "đẩy"],
  ["knock", "gõ (gõ bàn)"],
  ["break", "làm vỡ"],
  ["neighbor", "hàng xóm"],
  ["fill up", "lấp đầy"],
  ["stretch", "kéo dãn"],
  ["run out", "hết sạch"],
  ["rest", "lúc nghỉ ngơi"],
  ["spill", "làm đổ"],
  ["flush", "xả nước"],
  ["stay up", "thức muộn"],
  ["breath", "hơi thở"],
  ["sunrise", "bình minh"],
  ["phase", "giai đoạn"],
  ["leisure", "lúc rảnh rỗi"],
  ["series", "phim dài tập"],
  ["snooze", "giấc ngủ ngắn"],
  ["spare", "thừa"],
  ["sleep in", "ngủ nướng"],
  // Unit 3
  ["decline", "từ chối"],
  ["quit", "từ bỏ"],
  ["hang out", "đi chơi"],
  ["exercise", "thể dục"],
  ["calendar", "lịch"],
  ["amazing", "tuyệt vời"],
  ["workplace", "cơ quan"],
  ["patient", "tuyệt vời"],
  ["almost", "hầu như"],
  ["grateful", "thấy biết ơn"],
  ["jogging", "đi bộ thể dục"],
  ["tip", "mẹo"],
  ["necessary", "cần thiết"],
  ["focus", "tập trung"],
  ["estimate", "ước lượng"],
  ["practice", "tập luyện"],
  ["minute", "phút"],
  ["efficient", "có hiệu suất cao"],
  ["burnout", "tình trạng kiệt sức"],
  ["agenda", "danh sách công việc"],
  ["assist", "hỗ trợ"],
  ["productive", "có năng suất"],
  ["workload", "khối lượng công việc"],
  ["news", "tin tức"],
  ["arrange", "sắp xếp"],
  ["follow up", "theo sát"],
  ["discipline", "kỷ luật"],
  ["plan ahead", "lên kế hoạch trước"],
  ["outcome", "kết quả"],
  ["period", "khoảng thời gian"],
  // Unit 4
  ["form", "đơn"],
  ["male", "đàn ông"],
  ["fill out", "điền vào"],
  ["female", "phụ nữ"],
  ["personal", "cá nhân"],
  ["birth", "lúc chào đời"],
  ["information", "thông tin"],
  ["middle", "ở giữa"],
  ["gender", "giới tính"],
  ["correct", "sửa lại"],
  ["nationality", "quốc tịch"],
  ["southern", "phía Nam, phương Nam"],
  ["hometown", "quê quán, quê nhà"],
  ["recently", "gần đây"],
  ["grow up", "lớn lên"],
  ["district", "quận, huyện"],
  ["northern", "phía Bắc, phương Bắc"],
  ["sign", "ký tên"],
  ["province", "tỉnh, thành"],
  ["type", "gõ (gõ phím)"],
  ["additional", "thêm"],
  ["identity", "danh tính"],
  ["previous", "trước đó"],
  ["interview", "phỏng vấn"],
  ["live with", "sống cùng với"],
  ["photograph", "ảnh"],
  ["favorite", "yêu thích"],
  ["permanent", "lâu dài"],
  ["introduction", "giới thiệu"],
  ["code", "mã"],
  // Unit 5
  ["career", "sự nghiệp"],
  ["several", "một vài"],
  ["suitable", "phù hợp"],
  ["engineer", "kỹ sư"],
  ["experience", "kinh nghiệm"],
  ["background", "bối cảnh, nền tảng"],
  ["struggle", "gắng sức"],
  ["decide", "quyết định"],
  ["passion", "đam mê"],
  ["inspiration", "cảm hứng"],
  ["develop", "phát triển"],
  ["detail", "chi tiết"],
  ["abroad", "ở nước ngoài"],
  ["specific", "cụ thể"],
  ["fit in", "hòa nhập"],
  ["future", "tương lai"],
  ["freelance", "lao động tự do"],
  ["specialist", "chuyên viên"],
  ["occupation", "nghề nghiệp"],
  ["achievement", "thành tựu"],
  ["acquire", "có được"],
  ["grade", "điểm"],
  ["degree", "bằng cấp"],
  ["primary", "(thuộc cấp) tiểu học"],
  ["suppose", "cho rằng"],
  ["motivation", "động lực"],
  ["attend", "tham dự"],
  ["university", "đại học"],
  ["major", "theo chuyên ngành"],
  ["dream", "mơ ước"],
  // Unit 6
  ["goal", "mục tiêu"],
  ["ability", "khả năng"],
  ["company", "công ty"],
  ["offer", "đưa đề nghị"],
  ["prepare", "chuẩn bị"],
  ["condition", "điều kiện"],
  ["hire", "tuyển dụng"],
  ["salary", "lương"],
  ["position", "vị trí"],
  ["bonus", "khoản thưởng"],
  ["insurance", "bảo hiểm"],
  ["assess", "đánh giá"],
  ["relevant", "liên quan"],
  ["weakness", "điểm yếu"],
  ["stand out", "nổi bật"],
  ["training", "đào tạo"],
  ["duty", "nhiệm vụ"],
  ["evaluate", "đánh giá"],
  ["process", "xử lý"],
  ["look forward to", "mong chờ"],
  ["rule", "luật lệ"],
  ["department", "phòng ban"],
  ["mission", "sứ mệnh"],
  ["temporary", "tạm thời"],
  ["failure", "thất bại"],
  ["appointment", "cuộc hẹn"],
  ["lesson", "bài học"],
  ["official", "chính thức"],
  ["qualify", "đủ tiêu chuẩn"],
  ["potential", "tiềm năng"],
  // Unit 7
  ["secretary", "thư ký"],
  ["due", "đến hạn"],
  ["folder", "thư mục, tập tài liệu"],
  ["internship", "kỳ thực tập"],
  ["print", "in"],
  ["put off", "hoãn lại"],
  ["colleague", "đồng nghiệp"],
  ["equipment", "thiết bị, dụng cụ"],
  ["report", "báo cáo"],
  ["solution giải pháp", "phút"],
  ["function", "chức năng"],
  ["presentation", "bài thuyết trình"],
  ["hand over", "bàn giao"],
  ["approve", "chấp nhận"],
  ["deadline", "hạn chót"],
  ["conference", "hội thảo"],
  ["meeting", "cuộc họp"],
  ["client", "khách hàng"],
  ["member", "thành viên"],
  ["fault", "lỗi"],
  ["call off", "hủy"],
  ["assistant", "trợ lý"],
  ["stamp", "con dấu, con tem"],
  ["retire", "nghỉ hưu"],
  ["feedback", "ý kiến phản hồi"],
  ["expert", "mang tính chuyên gia"],
  ["strategy", "chiến lược"],
  ["handle", "xử lý"],
  ["carry out", "thực hiện"],
  ["involve", "bao gồm"],
  // Unit 8
  ["notebook", "vở, sổ"],
  ["possible", "có thể"],
  ["blank", "trống"],
  ["expect", "kỳ vọng"],
  ["include", "bao gồm"],
  ["fall behind", "tụt lại phía sau"],
  ["semester", "kỳ học"],
  ["turn to", "tìm tới"],
  ["curious", "tò mò"],
  ["improve", "cải thiện"],
  ["lecture", "bài giảng"],
  ["physics", "vật lý"],
  ["textbook", "sách giáo khoa"],
  ["subject", "môn học"],
  ["chemistry", "hóa học"],
  ["literature", "văn học"],
  ["hostory", "lịch sử"],
  ["topic", "chủ đề"],
  ["math", "toán học"],
  ["final", "cuối cùng"],
  ["exam", "bài thi"],
  ["project", "dự án"],
  ["instruction", "hướng dẫn"],
  ["certificate", "giấy chứng nhận"],
  ["complete", "hoàn thành"],
  ["assignment", "bài tập"],
  ["hand in", "nộp"],
  ["example", "ví dụ"],
  ["result", "kết quả"],
  ["summary", "tóm tắt"],
  // Unit 9
  ["education", "việc giáo dục"],
  ["faculty", "khoa trong trường"],
  ["prize", "giải thưởng"],
  ["professor", "giáo sư"],
  ["freshman", "sinh viên năm nhất"],
  ["principal", "hiệu trưởng"],
  ["course", "khóa học"],
  ["drop out", "bỏ học"],
  ["curriculum", "chương trình học"],
  ["get into", "vào"],
  ["laboratory", "phòng thí nghiệm"],
  ["tutor", "dạy gia sư"],
  ["research", "bài nghiên cứu"],
  ["thesis", "luận văn"],
  ["cross out", "gạch bỏ"],
  ["join", "tham gia"],
  ["campus", "khuôn viên trường"],
  ["excellent", "xuất sắc"],
  ["guide", "hướng dẫn"],
  ["knowledge", "kiến thức"],
  ["absent", "vắng"],
  ["transcript", "bảng điểm"],
  ["club", "câu lạc bộ"],
  ["scholarship", "học bổng"],
  ["fee", "phí"],
  ["graduate", "tốt nghiệp"],
  ["uniform", "đồng phục"],
  ["calculator", "máy tính bỏ túi"],
  ["event", "sự kiện"],
  ["tool", "công cụ"],
  // Unit 10
  ["remain", "giữ nguyên"],
  ["fond of", "quý mến"],
  ["advice", "lời khuyên"],
  ["difference", "sự khác biệt"],
  ["trust", "tin tưởng"],
  ["stranger", "người lạ"],
  ["doubt", "nghi ngờ"],
  ["get along", "hòa đồng"],
  ["roommate", "bạn cùng phòng"],
  ["relationship", "mối quan hệ"],
  ["apart", "cách xa"],
  ["joy", "niềm vui"],
  ["loyal", "trung thành, chung thủy"],
  ["familiar", "quen thuộc"],
  ["count on", "tin cậy"],
  ["forever", "mãi mãi"],
  ["harmony", "sự hòa thuận"],
  ["reliable", "đáng tin cậy"],
  ["argue", "tranh cãi, tranh luận"],
  ["friendship", "tình bạn"],
  ["mention", "nhắc đến"],
  ["easy-going", "dễ tính"],
  ["gossip", "ngồi lê đôi mách"],
  ["text", "nhắn tin"],
  ["conversation", "cuộc hội thoại"],
  ["dear", "đáng mến"],
  ["reason", "lý do"],
  ["gift", "món quà"],
  ["laugh", "cười"],
  ["comfortable", "thoải mái"],
  // Unit 11
  ["minute", "phút"],

];

var rd = -1;

var begin = [...list_eng]

function loadVocabulary() {
  if($('#vie').html() == "_" && rd != -1) {
    begin.splice(rd,1)
  }
  changeDisplayNone();
  if(begin.length == 0) {
    begin = [...list_eng]
  }

  labelFooter()

  rd = Math.floor(Math.random() * begin.length);
  document.getElementById("eng").innerHTML = begin[rd][0];
}

function changeDisplay() {
  // document.getElementById("vie").style.display = "block";
  document.getElementById("vie").innerHTML = begin[rd][1].toUpperCase();
}

function changeDisplayNone() {
  //document.getElementById("vie").style.display = "none";
  document.getElementById("vie").innerHTML = "_";
}

$(document).ready(function () {
  labelFooter()
  loadVocabulary();
});

function labelFooter(){
  $("#sum_vocabulary").html(`Hoàn thành: ${begin.length} / ${list_eng.length}`);
}